feat: quote behavior changes for seller
Kibo-UCP/nextjs-storefront-seller pull request #12
Opened 2023-12-08 14:15 UTC by kibo-chandradeeptalaha

2023-12-19 07:19 UTC, Kibo-TriptiV requested changes
Please check review comments.

2023-12-19 07:19 UTC, Kibo-TriptiV commented on components/b2b/seller/SellerQuoteActions/SellerQuoteActions.spec.tsx
> +  // it('should disable clear changes button if quote is InReview/Completed status and quote is not in draft mode', () => {
why commented tests?

2023-12-19 07:19 UTC, Kibo-TriptiV commented on components/b2b/B2BProductDetailsTable/B2BProductDetailsTable.tsx
> +                {QuoteStatus[status as string] === QuoteStatus.Completed ||
Can we have these condition on getters and behave based on seller or buyer?

2023-12-19 07:19 UTC, Kibo-TriptiV commented on components/b2b/seller/SellerQuoteActions/SellerQuoteActions.tsx
> +                      // disabled={hasDraft as boolean}
remove commented code

2024-01-05 07:55 UTC, kibo-chandradeeptalaha commented on components/b2b/B2BProductDetailsTable/B2BProductDetailsTable.tsx
> +                {QuoteStatus[status as string] === QuoteStatus.Completed ||
Will do this in main branch

2024-01-05 08:13 UTC, kibo-chandradeeptalaha commented on components/b2b/seller/SellerQuoteActions/SellerQuoteActions.spec.tsx
> +  // it('should disable clear changes button if quote is InReview/Completed status and quote is not in draft mode', () => {
removed

2024-01-05 08:14 UTC, kibo-chandradeeptalaha commented on components/b2b/seller/SellerQuoteActions/SellerQuoteActions.tsx
> +                      // disabled={hasDraft as boolean}
done

2024-01-05 08:27 UTC, Kibo-TriptiV approved these changes

2024-01-05 08:28 UTC, merged